load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "init",
    srcs = ["__init__.py"],
    imports = [".."],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "main",
    srcs = ["main.py"],
    imports = [".."],
    main = "main.py",
    visibility = ["//visibility:public"],
    deps = [
        ":init",
        "//printer_debugger/store",
        "//printer_debugger/web",
        "@pypi//uvicorn",
    ],
)

