"""Composition-root wiring tests: startup credentials, index build, the turn, approval, and locus.

The Agent SDK is never invoked here — the turn runs against a fake ``AgentClient`` (the pattern from
``orchestration_test``), and the approval gate and submission locus are driven directly. Every test
carries a one-line doc comment stating the behaviour it verifies.
"""

from __future__ import annotations

import asyncio
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory

from fastapi.testclient import TestClient

from printer_debugger import composition
from printer_debugger.orchestration import turn
from printer_debugger.printer.danger import Classification
from printer_debugger.store.artifact_store import LocalFilesystemArtifactStore
from printer_debugger.store.db import Database
from printer_debugger.store.models import ApprovalDecision, TokenUsage
from printer_debugger.store.structured_store import StructuredStore
from printer_debugger.web.app import AppContext, create_app
from printer_debugger.web.security import AuthConfig, AuthMode


def _gcode_fixture(layers: int = 4) -> str:
    """A minimal G-code text with one extruding move per rising Z, so the indexer finds layers."""
    lines = ["; HEADER_BLOCK_START", "; generated by test", "; HEADER_BLOCK_END", "G28", "G90"]
    for i in range(1, layers + 1):
        z = round(0.2 * i, 2)
        lines.append(f"G1 Z{z} F600")
        lines.append(f"G1 X{10 + i} Y{10 + i} E{i}.0 F1200")
    return "\n".join(lines) + "\n"


class _FakeAgentClient:
    """Yields a scripted event stream for the turn loop, standing in for the real SDK client."""

    def __init__(self, events: list) -> None:
        self._events = events

    async def run_turn(self, session_id: str, user_content: list):
        for event in self._events:
            yield event


class StartupCredentialTest(unittest.TestCase):
    """Startup requires the OAuth token and reads model/effort from the environment."""

    def test_missing_token_crashes(self) -> None:
        """An absent or blank OAuth token raises StartupError so the process never serves."""
        with self.assertRaises(composition.StartupError):
            composition.require_oauth_token({})
        with self.assertRaises(composition.StartupError):
            composition.require_oauth_token({composition.OAUTH_ENV: "   "})

    def test_present_token_returned(self) -> None:
        """A present token is returned verbatim for passing on to the SDK."""
        self.assertEqual(
            composition.require_oauth_token({composition.OAUTH_ENV: "fake-token"}), "fake-token"
        )

    def test_model_effort_defaults_and_overrides(self) -> None:
        """Model/effort default to Opus at medium effort and honour the PD_* overrides."""
        self.assertEqual(
            composition.resolve_model_effort({}),
            (composition.DEFAULT_MODEL, composition.DEFAULT_EFFORT),
        )
        self.assertEqual(
            composition.resolve_model_effort({"PD_MODEL": "m", "PD_EFFORT": "high"}), ("m", "high")
        )


class _StoreFixture(unittest.TestCase):
    """A migrated store plus a filesystem artifact store in a temp directory."""

    def setUp(self) -> None:
        self._dir = TemporaryDirectory()
        self.db = Database(Path(self._dir.name) / "t.db")
        self.db.migrate()
        self.store = StructuredStore(self.db)
        self.artifacts = LocalFilesystemArtifactStore(Path(self._dir.name) / "artifacts")

    def tearDown(self) -> None:
        self.db.close()
        self._dir.cleanup()


class UploadIndexTest(_StoreFixture):
    """Uploading G-code builds and stores an index that the gcode tools can answer over."""

    def test_gcode_upload_builds_and_stores_index(self) -> None:
        """A G-code upload records a file_index row, and load_gcode_tools answers over it."""
        context = AppContext(
            store=self.store,
            auth=AuthConfig(mode=AuthMode.LOCAL),
            artifacts=self.artifacts,
            on_upload=lambda artifact, body: composition.build_index_for_upload(
                self.store, self.artifacts, artifact, body
            ),
        )
        client = TestClient(create_app(context))
        session = self.store.create_session(name="s")
        response = client.post(
            f"/sessions/{session.id}/files",
            content=_gcode_fixture().encode("utf-8"),
            headers={"X-Filename": "part.gcode", "Content-Type": "text/plain"},
        )
        self.assertEqual(response.json()["kind"], "gcode")
        artifact_id = response.json()["artifact_id"]
        file_index = self.store.get_file_index(artifact_id)
        self.assertIsNotNone(file_index)
        self.assertEqual(file_index.kind.value, "gcode")

        tools = composition.load_gcode_tools(self.store, self.artifacts, session.id)
        self.assertIsNotNone(tools)
        self.assertGreater(tools.get_layer_table()["count"], 0)

    def test_non_gcode_upload_builds_no_index(self) -> None:
        """A .3mf upload stores the blob but builds no index (mesh read on demand)."""
        stored: list = []
        context = AppContext(
            store=self.store,
            auth=AuthConfig(mode=AuthMode.LOCAL),
            artifacts=self.artifacts,
            on_upload=lambda artifact, body: composition.build_index_for_upload(
                self.store, self.artifacts, artifact, body
            ),
        )
        client = TestClient(create_app(context))
        session = self.store.create_session(name="s")
        response = client.post(
            f"/sessions/{session.id}/files",
            content=b"PK\x03\x04 fake 3mf",
            headers={"X-Filename": "part.3mf", "Content-Type": "application/octet-stream"},
        )
        self.assertEqual(response.json()["kind"], "project")
        self.assertIsNone(self.store.get_file_index(response.json()["artifact_id"]))


class OnMessageTurnTest(_StoreFixture):
    """on_message runs a turn against a fake client, persisting it and streaming to the hub."""

    def test_turn_persists_and_streams(self) -> None:
        """A turn stores the user and assistant messages and pushes assistant/tool SSE events."""
        from printer_debugger.web.sse import SseHub

        hub = SseHub()
        events = [
            turn.TextEvent("looking..."),
            turn.ToolStartEvent("gcode", "get_header", {}, ref="t1"),
            turn.ToolResultEvent("t1", "header"),
            turn.AssistantMessageEvent([{"type": "text", "text": "answer"}]),
            turn.UsageEvent(TokenUsage(input_tokens=10, output_tokens=5)),
        ]
        on_message = composition.make_on_message(
            self.store, hub, lambda _sid: _FakeAgentClient(events)
        )
        session = self.store.create_session(name="s")
        asyncio.run(on_message(session.id, [{"type": "text", "text": "why?"}]))

        roles = [m.role.value for m in self.store.list_messages(session.id)]
        self.assertEqual(roles, ["user", "assistant"])
        self.assertEqual(len(self.store.list_tool_calls(session.id)), 1)
        kinds = [e.kind for e in hub.missed_since(session.id, 0)]
        self.assertIn("assistant", kinds)
        self.assertIn("tool", kinds)


class ApproveBridgeTest(_StoreFixture):
    """The approve bridge publishes a proposal, routes the vote through resolve, and records it."""

    def test_approve_routes_to_gate_resolve_and_records(self) -> None:
        """A published proposal, resolved as approved, returns True and records an approved row."""
        from printer_debugger.web.sse import SseHub

        hub = SseHub()
        gate = composition.make_gate(self.store, hub)
        session = self.store.create_session(name="s")
        approve = composition.make_approve(self.store, gate, session.id)

        async def scenario() -> bool:
            task = asyncio.create_task(approve("G28", ()))
            await asyncio.sleep(0)  # let the proposal publish and the gate reach its await.
            proposal = hub.missed_since(session.id, 0)[0]
            tool_call_id = proposal.data["tool_call_id"]
            self.assertTrue(gate.resolve(tool_call_id, True, "tester"))
            approved = await task
            self._tool_call_id = tool_call_id
            return approved

        self.assertTrue(asyncio.run(scenario()))
        approval = self.store.get_approval(self._tool_call_id)
        self.assertEqual(approval.decision, ApprovalDecision.APPROVED)
        self.assertEqual(approval.decided_by, "tester")

    def test_reject_records_rejection(self) -> None:
        """A proposal resolved as rejected returns False and records a rejected row."""
        from printer_debugger.web.sse import SseHub

        hub = SseHub()
        gate = composition.make_gate(self.store, hub)
        session = self.store.create_session(name="s")
        approve = composition.make_approve(self.store, gate, session.id)

        async def scenario() -> bool:
            task = asyncio.create_task(approve("G28", ()))
            await asyncio.sleep(0)
            tool_call_id = hub.missed_since(session.id, 0)[0].data["tool_call_id"]
            gate.resolve(tool_call_id, False, "tester")
            self._tool_call_id = tool_call_id
            return await task

        self.assertFalse(asyncio.run(scenario()))
        self.assertEqual(
            self.store.get_approval(self._tool_call_id).decision, ApprovalDecision.REJECTED
        )


class SubmissionLocusTest(_StoreFixture):
    """A gated command is submitted exactly once: the gate decides, the tool submits."""

    def test_gate_does_not_submit_and_tool_submits_once(self) -> None:
        """Approving at the gate submits nothing; propose_command then submits exactly one POST."""
        from printer_debugger.printer.moonraker import MoonrakerClient
        from printer_debugger.printer.tools import PrinterTools
        from printer_debugger.web.sse import SseHub

        posts: list[tuple[str, str]] = []

        def transport(method: str, url: str, body: bytes | None):
            posts.append((method, url))
            return 200, b"{}"

        hub = SseHub()
        gate = composition.make_gate(self.store, hub)
        session = self.store.create_session(name="s")
        approve = composition.make_approve(self.store, gate, session.id)

        async def gate_scenario() -> bool:
            task = asyncio.create_task(approve("G28", ()))
            await asyncio.sleep(0)
            tool_call_id = hub.missed_since(session.id, 0)[0].data["tool_call_id"]
            gate.resolve(tool_call_id, True, "tester")
            return await task

        self.assertTrue(asyncio.run(gate_scenario()))
        self.assertEqual(posts, [], "the gate decides only; it must not submit to the printer")

        submit = composition.make_command_submitter("http://printer:7125", transport)
        tools = PrinterTools(
            MoonrakerClient(base_url="http://printer:7125", transport=transport), gate=submit
        )
        result = tools.propose_command("G28")
        self.assertTrue(result["executed"])
        submit_posts = [p for p in posts if p[0] == "POST" and "gcode/script" in p[1]]
        self.assertEqual(len(submit_posts), 1, "the command reaches the printer exactly once")

    def test_submitter_reports_unreachable(self) -> None:
        """The submitter reports an unreachable printer instead of raising into the tool."""
        from printer_debugger.printer.moonraker import PrinterUnreachable

        def transport(method: str, url: str, body: bytes | None):
            raise PrinterUnreachable("no route")

        submit = composition.make_command_submitter("http://printer:7125", transport)
        outcome = submit("G28", Classification(flags=(), refused=False))
        self.assertFalse(outcome["executed"])
        self.assertIn("unreachable", outcome["reason"])


if __name__ == "__main__":
    unittest.main()
