"""Composition-root wiring tests: startup credentials, index build, the turn, approval, and locus.

The Agent SDK is never invoked here — the turn runs against a fake ``AgentClient`` (the pattern from
``orchestration_test``), and the approval gate and submission locus are driven directly. Every test
carries a one-line doc comment stating the behaviour it verifies.
"""

from __future__ import annotations

import asyncio
import io
import logging
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory

from fastapi.testclient import TestClient

from printer_debugger import composition
from printer_debugger.logging_setup import PACKAGE_LOGGER, configure_logging
from printer_debugger.orchestration import turn
from printer_debugger.printer.danger import Classification
from printer_debugger.store.artifact_store import LocalFilesystemArtifactStore
from printer_debugger.store.errors import ArtifactNotFoundError
from printer_debugger.store.db import Database
from printer_debugger.store.models import (
    ApprovalDecision,
    Artifact,
    ArtifactKind,
    BindingReason,
    PrinterStatus,
    TokenUsage,
)
from printer_debugger.store.structured_store import StructuredStore
from printer_debugger.web.app import AppContext, create_app
from printer_debugger.web.security import AuthConfig, AuthMode


def _gcode_fixture(layers: int = 4) -> str:
    """A minimal G-code text with one extruding move per rising Z, so the indexer finds layers."""
    lines = ["; HEADER_BLOCK_START", "; generated by test", "; HEADER_BLOCK_END", "G28", "G90"]
    for i in range(1, layers + 1):
        z = round(0.2 * i, 2)
        lines.append(f"G1 Z{z} F600")
        lines.append(f"G1 X{10 + i} Y{10 + i} E{i}.0 F1200")
    return "\n".join(lines) + "\n"


class _FakeAgentClient:
    """Yields a scripted event stream for the turn loop, standing in for the real SDK client."""

    def __init__(self, events: list) -> None:
        self._events = events

    async def run_turn(self, session_id: str, user_content: list):
        for event in self._events:
            yield event


class StartupCredentialTest(unittest.TestCase):
    """Startup requires the OAuth token and reads model/effort from the environment."""

    def test_missing_token_crashes(self) -> None:
        """An absent or blank OAuth token raises StartupError so the process never serves."""
        with self.assertRaises(composition.StartupError):
            composition.require_oauth_token({})
        with self.assertRaises(composition.StartupError):
            composition.require_oauth_token({composition.OAUTH_ENV: "   "})

    def test_present_token_returned(self) -> None:
        """A present token is returned verbatim for passing on to the SDK."""
        self.assertEqual(
            composition.require_oauth_token({composition.OAUTH_ENV: "fake-token"}), "fake-token"
        )

    def test_model_effort_defaults_and_overrides(self) -> None:
        """Model/effort default to Opus at medium effort and honour the PD_* overrides."""
        self.assertEqual(
            composition.resolve_model_effort({}),
            (composition.DEFAULT_MODEL, composition.DEFAULT_EFFORT),
        )
        self.assertEqual(
            composition.resolve_model_effort({"PD_MODEL": "m", "PD_EFFORT": "high"}), ("m", "high")
        )


class _StoreFixture(unittest.TestCase):
    """A migrated store plus a filesystem artifact store in a temp directory."""

    def setUp(self) -> None:
        self._dir = TemporaryDirectory()
        self.db = Database(Path(self._dir.name) / "t.db")
        self.db.migrate()
        self.store = StructuredStore(self.db)
        self.artifacts = LocalFilesystemArtifactStore(Path(self._dir.name) / "artifacts")

    def tearDown(self) -> None:
        self.db.close()
        self._dir.cleanup()


class UploadIndexTest(_StoreFixture):
    """Uploading G-code builds and stores an index that the gcode tools can answer over."""

    def test_gcode_upload_builds_and_stores_index(self) -> None:
        """A G-code upload records a file_index row, and load_gcode_tools answers over it."""
        context = AppContext(
            store=self.store,
            auth=AuthConfig(mode=AuthMode.LOCAL),
            artifacts=self.artifacts,
            on_upload=lambda artifact, body: composition.build_index_for_upload(
                self.store, self.artifacts, artifact, body
            ),
        )
        client = TestClient(create_app(context))
        session = self.store.create_session(name="s")
        response = client.post(
            f"/sessions/{session.id}/files",
            content=_gcode_fixture().encode("utf-8"),
            headers={"X-Filename": "part.gcode", "Content-Type": "text/plain"},
        )
        self.assertEqual(response.json()["kind"], "gcode")
        artifact_id = response.json()["artifact_id"]
        file_index = self.store.get_file_index(artifact_id)
        self.assertIsNotNone(file_index)
        self.assertEqual(file_index.kind.value, "gcode")

        tools = composition.load_gcode_tools(self.store, self.artifacts, session.id)
        self.assertIsNotNone(tools)
        self.assertGreater(tools.get_layer_table()["count"], 0)

    def test_non_gcode_upload_builds_no_index(self) -> None:
        """A .3mf upload stores the blob but builds no index (mesh read on demand)."""
        stored: list = []
        context = AppContext(
            store=self.store,
            auth=AuthConfig(mode=AuthMode.LOCAL),
            artifacts=self.artifacts,
            on_upload=lambda artifact, body: composition.build_index_for_upload(
                self.store, self.artifacts, artifact, body
            ),
        )
        client = TestClient(create_app(context))
        session = self.store.create_session(name="s")
        response = client.post(
            f"/sessions/{session.id}/files",
            content=b"PK\x03\x04 fake 3mf",
            headers={"X-Filename": "part.3mf", "Content-Type": "application/octet-stream"},
        )
        self.assertEqual(response.json()["kind"], "project")
        self.assertIsNone(self.store.get_file_index(response.json()["artifact_id"]))


_PROJECT_3MF = (
    Path(__file__).resolve().parent / "indexing" / "testdata" / "project.3mf"
)


class ArtifactReaderTest(_StoreFixture):
    """make_artifact_reader returns an artifact's bytes and content type, or raises when absent."""

    def test_reads_stored_bytes_and_content_type(self) -> None:
        """The reader returns the stored blob bytes and the artifact's content type for an id."""
        session = self.store.create_session(name="s")
        blob_key = f"sessions/{session.id}/photo.jpg"
        self.artifacts.put(blob_key, io.BytesIO(b"\xff\xd8jpeg"))
        artifact = self.store.add_artifact(
            session_id=session.id, kind=ArtifactKind.PHOTO, blob_key=blob_key,
            size_bytes=5, content_type="image/jpeg",
        )
        reader = composition.make_artifact_reader(self.store, self.artifacts)
        data, content_type = reader(artifact.id)
        self.assertEqual(data, b"\xff\xd8jpeg")
        self.assertEqual(content_type, "image/jpeg")

    def test_unknown_artifact_raises(self) -> None:
        """Reading an artifact id with no row raises ArtifactNotFoundError rather than returning."""
        reader = composition.make_artifact_reader(self.store, self.artifacts)
        with self.assertRaises(ArtifactNotFoundError):
            reader("art_missing")


class LoadProjectToolsTest(_StoreFixture):
    """load_project_tools reconstructs ProjectTools over an uploaded .3mf, or returns None."""

    def _store_project(self, session_id: str) -> None:
        """Store the real .3mf fixture as a PROJECT artifact of the session."""
        data = _PROJECT_3MF.read_bytes()
        blob_key = f"sessions/{session_id}/project.3mf"
        self.artifacts.put(blob_key, io.BytesIO(data))
        self.store.add_artifact(
            session_id=session_id,
            kind=ArtifactKind.PROJECT,
            blob_key=blob_key,
            size_bytes=len(data),
            content_type="application/octet-stream",
        )

    def test_returns_tools_answering_over_the_project(self) -> None:
        """An uploaded .3mf yields tools whose settings and dimensions answer sensibly."""
        session = self.store.create_session(name="s")
        self._store_project(session.id)
        tools = composition.load_project_tools(self.store, self.artifacts, session.id)
        self.assertIsNotNone(tools)
        settings = tools.get_settings()
        self.assertIn("keys", settings)
        self.assertTrue(settings["keys"])
        dimensions = tools.get_object_dimensions()
        self.assertGreater(dimensions["height"], 0)
        self.assertGreater(dimensions["volume"], 0)

    def test_no_project_returns_none(self) -> None:
        """A session with no PROJECT artifact returns None."""
        session = self.store.create_session(name="s")
        self.assertIsNone(
            composition.load_project_tools(self.store, self.artifacts, session.id)
        )


class AutoBindFromProjectTest(_StoreFixture):
    """auto_bind_from_project binds a session to a matching printer, conservatively and once."""

    def _seed_printer(self, name: str) -> str:
        """Create a known printer with the given name and return its id."""
        return self.store.create_printer(
            name=name,
            kb_section="## " + name,
            kb_content_hash="hash-" + name,
            status=PrinterStatus.COMPLETE,
            address="http://printer.local",
        ).id

    def _project_artifact(self, session_id: str) -> tuple[Artifact, bytes]:
        """Store the real .3mf fixture as a PROJECT artifact and return it with its bytes."""
        data = _PROJECT_3MF.read_bytes()
        blob_key = f"sessions/{session_id}/project.3mf"
        self.artifacts.put(blob_key, io.BytesIO(data))
        artifact = self.store.add_artifact(
            session_id=session_id,
            kind=ArtifactKind.PROJECT,
            blob_key=blob_key,
            size_bytes=len(data),
            content_type="application/octet-stream",
        )
        return artifact, data

    def _malformed_project_artifact(self, session_id: str) -> Artifact:
        """Store an empty (unparseable) .3mf as a PROJECT artifact and return it."""
        blob_key = f"sessions/{session_id}/project.3mf"
        self.artifacts.put(blob_key, io.BytesIO(b""))
        return self.store.add_artifact(
            session_id=session_id,
            kind=ArtifactKind.PROJECT,
            blob_key=blob_key,
            size_bytes=0,
            content_type="application/octet-stream",
        )

    def test_single_printer_binds_detected(self) -> None:
        """One known printer plus a .3mf upload auto-binds it (DETECTED) and logs the decision."""
        printer_id = self._seed_printer("Some Other Printer")
        session = self.store.create_session(name="s")
        artifact, body = self._project_artifact(session.id)
        with self.assertLogs("printer_debugger.composition", level="INFO") as cm:
            bound = composition.auto_bind_from_project(
                self.store, self.artifacts, artifact, body
            )
        self.assertEqual(bound, printer_id)
        self.assertEqual(self.store.get_session(session.id).printer_id, printer_id)
        bindings = self.store.list_bindings(session.id)
        self.assertEqual(bindings[-1].reason, BindingReason.DETECTED)
        self.assertTrue(
            any("single known printer 'Some Other Printer'" in line for line in cm.output),
            cm.output,
        )

    def test_single_printer_binds_even_when_identity_read_fails(self) -> None:
        """A single printer binds (DETECTED) even when the .3mf identity cannot be read at all."""
        printer_id = self._seed_printer("Some Other Printer")
        session = self.store.create_session(name="s")
        artifact = self._malformed_project_artifact(session.id)
        with self.assertLogs("printer_debugger.composition", level="INFO") as cm:
            bound = composition.auto_bind_from_project(
                self.store, self.artifacts, artifact, b""
            )
        self.assertEqual(bound, printer_id)
        self.assertEqual(self.store.get_session(session.id).printer_id, printer_id)
        self.assertTrue(
            any("single known printer 'Some Other Printer'" in line for line in cm.output),
            cm.output,
        )

    def test_no_printers_skips(self) -> None:
        """With no known printers, nothing binds and the skip decision is logged."""
        session = self.store.create_session(name="s")
        artifact, body = self._project_artifact(session.id)
        with self.assertLogs("printer_debugger.composition", level="INFO") as cm:
            bound = composition.auto_bind_from_project(
                self.store, self.artifacts, artifact, body
            )
        self.assertIsNone(bound)
        self.assertIsNone(self.store.get_session(session.id).printer_id)
        self.assertTrue(
            any("no known printers; skipping" in line for line in cm.output), cm.output
        )

    def test_multiple_printers_one_match_binds_match(self) -> None:
        """With several printers, only the name-matching one binds; the match is logged."""
        match_id = self._seed_printer("Voron v2")
        other_id = self._seed_printer("Prusa MK4")
        session = self.store.create_session(name="s")
        artifact, body = self._project_artifact(session.id)
        with self.assertLogs("printer_debugger.composition", level="INFO") as cm:
            bound = composition.auto_bind_from_project(
                self.store, self.artifacts, artifact, body
            )
        self.assertEqual(bound, match_id)
        self.assertEqual(self.store.get_session(session.id).printer_id, match_id)
        self.assertNotEqual(bound, other_id)
        self.assertTrue(any("project identity = " in line for line in cm.output), cm.output)
        self.assertTrue(
            any("matched 'Voron v2'; bound (DETECTED)" in line for line in cm.output),
            cm.output,
        )

    def test_multiple_printers_no_match_leaves_unbound(self) -> None:
        """With several printers and no match, nothing binds; identity and names are logged."""
        self._seed_printer("Prusa MK4")
        self._seed_printer("Bambu X1C")
        session = self.store.create_session(name="s")
        artifact, body = self._project_artifact(session.id)
        with self.assertLogs("printer_debugger.composition", level="INFO") as cm:
            bound = composition.auto_bind_from_project(
                self.store, self.artifacts, artifact, body
            )
        self.assertIsNone(bound)
        self.assertIsNone(self.store.get_session(session.id).printer_id)
        no_match = [line for line in cm.output if "no unique match" in line]
        self.assertTrue(no_match, cm.output)
        self.assertIn("Prusa MK4", no_match[0])
        self.assertIn("Bambu X1C", no_match[0])
        self.assertIn("left for the manual picker", no_match[0])

    def test_existing_binding_not_overwritten(self) -> None:
        """A session already bound to a printer is left untouched, and the skip is logged."""
        chosen_id = self._seed_printer("Voron v2")
        session = self.store.create_session(name="s")
        self.store.bind_printer(session.id, chosen_id, BindingReason.CHOSEN)
        artifact, body = self._project_artifact(session.id)
        with self.assertLogs("printer_debugger.composition", level="INFO") as cm:
            bound = composition.auto_bind_from_project(
                self.store, self.artifacts, artifact, body
            )
        self.assertIsNone(bound)
        self.assertEqual(self.store.get_session(session.id).printer_id, chosen_id)
        self.assertEqual(len(self.store.list_bindings(session.id)), 1)
        self.assertTrue(
            any("already bound" in line and "skipping" in line for line in cm.output),
            cm.output,
        )

    def test_non_project_artifact_returns_none(self) -> None:
        """A non-PROJECT artifact (e.g. a photo) binds nothing and emits no auto-bind decision."""
        self._seed_printer("Voron v2")
        session = self.store.create_session(name="s")
        blob_key = f"sessions/{session.id}/photo.jpg"
        self.artifacts.put(blob_key, io.BytesIO(b"\xff\xd8jpeg"))
        artifact = self.store.add_artifact(
            session_id=session.id,
            kind=ArtifactKind.PHOTO,
            blob_key=blob_key,
            size_bytes=5,
            content_type="image/jpeg",
        )
        with self.assertNoLogs("printer_debugger.composition", level="INFO"):
            bound = composition.auto_bind_from_project(
                self.store, self.artifacts, artifact, b"\xff\xd8jpeg"
            )
        self.assertIsNone(bound)
        self.assertIsNone(self.store.get_session(session.id).printer_id)

    def test_malformed_body_does_not_raise(self) -> None:
        """With several printers, a malformed .3mf body is swallowed: no bind, identity logged."""
        self._seed_printer("Voron v2")
        self._seed_printer("Prusa MK4")
        session = self.store.create_session(name="s")
        artifact = self._malformed_project_artifact(session.id)
        with self.assertLogs("printer_debugger.composition", level="INFO") as cm:
            bound = composition.auto_bind_from_project(
                self.store, self.artifacts, artifact, b""
            )
        self.assertIsNone(bound)
        self.assertIsNone(self.store.get_session(session.id).printer_id)
        self.assertTrue(
            any("could not read project identity" in line for line in cm.output), cm.output
        )


class RenderSinkTest(_StoreFixture):
    """The render sink persists a PNG into the artifact store and returns a resolvable reference."""

    def test_render_is_stored_and_reference_resolves(self) -> None:
        """get_object_render stores PNG bytes and returns a /artifacts reference serve_artifact
        resolves to those bytes."""
        session = self.store.create_session(name="s")
        data = _PROJECT_3MF.read_bytes()
        blob_key = f"sessions/{session.id}/project.3mf"
        self.artifacts.put(blob_key, io.BytesIO(data))
        self.store.add_artifact(
            session_id=session.id,
            kind=ArtifactKind.PROJECT,
            blob_key=blob_key,
            size_bytes=len(data),
            content_type="application/octet-stream",
        )
        tools = composition.load_project_tools(self.store, self.artifacts, session.id)
        assert tools is not None
        result = tools.get_object_render(view="iso", width=64, height=64)
        reference = result["artifact"]
        self.assertIsNotNone(reference)
        self.assertTrue(reference.startswith("/artifacts/"))

        artifact_id = reference.rsplit("/", 1)[-1]
        artifact = self.store.get_artifact(artifact_id)
        self.assertIsNotNone(artifact)
        self.assertEqual(artifact.content_type, "image/png")
        with self.artifacts.open(artifact.blob_key) as blob:
            stored = blob.read()
        self.assertTrue(stored.startswith(b"\x89PNG"))


class OnMessageTurnTest(_StoreFixture):
    """on_message runs a turn against a fake client, persisting it and streaming to the hub."""

    def test_turn_persists_and_streams(self) -> None:
        """A turn stores the user and assistant messages and pushes assistant/tool SSE events."""
        from printer_debugger.web.sse import SseHub

        hub = SseHub()
        events = [
            turn.TextEvent("looking..."),
            turn.ToolStartEvent("gcode", "get_header", {}, ref="t1"),
            turn.ToolResultEvent("t1", "header"),
            turn.AssistantMessageEvent([{"type": "text", "text": "answer"}]),
            turn.UsageEvent(TokenUsage(input_tokens=10, output_tokens=5)),
        ]
        on_message = composition.make_on_message(
            self.store, hub, lambda _sid: _FakeAgentClient(events)
        )
        session = self.store.create_session(name="s")
        asyncio.run(on_message(session.id, [{"type": "text", "text": "why?"}]))

        roles = [m.role.value for m in self.store.list_messages(session.id)]
        self.assertEqual(roles, ["user", "assistant"])
        self.assertEqual(len(self.store.list_tool_calls(session.id)), 1)
        kinds = [e.kind for e in hub.missed_since(session.id, 0)]
        self.assertIn("assistant", kinds)
        self.assertIn("tool", kinds)


class ForwardEventTest(unittest.TestCase):
    """_forward_event publishes each turn event to the session's viewers on the right channel."""

    def test_error_event_published_on_agent_error_channel(self) -> None:
        """An ErrorEvent is published on the 'agent_error' channel carrying its message."""
        from printer_debugger.web.sse import SseHub

        hub = SseHub()
        composition._forward_event(
            hub, "s1", turn.ErrorEvent("The agent turn failed (subtype=error_max_turns)")
        )
        events = hub.missed_since("s1", 0)
        self.assertEqual([e.kind for e in events], ["agent_error"])
        self.assertIn("error_max_turns", events[0].data["message"])

    def test_text_event_still_published_on_assistant_channel(self) -> None:
        """A TextEvent still publishes on the 'assistant' channel (existing behaviour preserved)."""
        from printer_debugger.web.sse import SseHub

        hub = SseHub()
        composition._forward_event(hub, "s1", turn.TextEvent("looking..."))
        events = hub.missed_since("s1", 0)
        self.assertEqual([e.kind for e in events], ["assistant"])
        self.assertEqual(events[0].data["text"], "looking...")


class ApproveBridgeTest(_StoreFixture):
    """The approve bridge publishes a proposal, routes the vote through resolve, and records it."""

    def test_approve_routes_to_gate_resolve_and_records(self) -> None:
        """A published proposal, resolved as approved, returns True and records an approved row."""
        from printer_debugger.web.sse import SseHub

        hub = SseHub()
        gate = composition.make_gate(self.store, hub)
        session = self.store.create_session(name="s")
        approve = composition.make_approve(self.store, gate, session.id)

        async def scenario() -> bool:
            task = asyncio.create_task(approve("G28", ()))
            await asyncio.sleep(0)  # let the proposal publish and the gate reach its await.
            proposal = hub.missed_since(session.id, 0)[0]
            tool_call_id = proposal.data["tool_call_id"]
            self.assertTrue(gate.resolve(tool_call_id, True, "tester"))
            approved = await task
            self._tool_call_id = tool_call_id
            return approved

        self.assertTrue(asyncio.run(scenario()))
        approval = self.store.get_approval(self._tool_call_id)
        self.assertEqual(approval.decision, ApprovalDecision.APPROVED)
        self.assertEqual(approval.decided_by, "tester")

    def test_reject_records_rejection(self) -> None:
        """A proposal resolved as rejected returns False and records a rejected row."""
        from printer_debugger.web.sse import SseHub

        hub = SseHub()
        gate = composition.make_gate(self.store, hub)
        session = self.store.create_session(name="s")
        approve = composition.make_approve(self.store, gate, session.id)

        async def scenario() -> bool:
            task = asyncio.create_task(approve("G28", ()))
            await asyncio.sleep(0)
            tool_call_id = hub.missed_since(session.id, 0)[0].data["tool_call_id"]
            gate.resolve(tool_call_id, False, "tester")
            self._tool_call_id = tool_call_id
            return await task

        self.assertFalse(asyncio.run(scenario()))
        self.assertEqual(
            self.store.get_approval(self._tool_call_id).decision, ApprovalDecision.REJECTED
        )


class SubmissionLocusTest(_StoreFixture):
    """A gated command is submitted exactly once: the gate decides, the tool submits."""

    def test_gate_does_not_submit_and_tool_submits_once(self) -> None:
        """Approving at the gate submits nothing; propose_command then submits exactly one POST."""
        from printer_debugger.printer.moonraker import MoonrakerClient
        from printer_debugger.printer.tools import PrinterTools
        from printer_debugger.web.sse import SseHub

        posts: list[tuple[str, str]] = []

        def transport(method: str, url: str, body: bytes | None):
            posts.append((method, url))
            return 200, b"{}"

        hub = SseHub()
        gate = composition.make_gate(self.store, hub)
        session = self.store.create_session(name="s")
        approve = composition.make_approve(self.store, gate, session.id)

        async def gate_scenario() -> bool:
            task = asyncio.create_task(approve("G28", ()))
            await asyncio.sleep(0)
            tool_call_id = hub.missed_since(session.id, 0)[0].data["tool_call_id"]
            gate.resolve(tool_call_id, True, "tester")
            return await task

        self.assertTrue(asyncio.run(gate_scenario()))
        self.assertEqual(posts, [], "the gate decides only; it must not submit to the printer")

        submit = composition.make_command_submitter("http://printer:7125", transport)
        tools = PrinterTools(
            MoonrakerClient(base_url="http://printer:7125", transport=transport), gate=submit
        )
        result = tools.propose_command("G28")
        self.assertTrue(result["executed"])
        submit_posts = [p for p in posts if p[0] == "POST" and "gcode/script" in p[1]]
        self.assertEqual(len(submit_posts), 1, "the command reaches the printer exactly once")

    def test_submitter_reports_unreachable(self) -> None:
        """The submitter reports an unreachable printer instead of raising into the tool."""
        from printer_debugger.printer.moonraker import PrinterUnreachable

        def transport(method: str, url: str, body: bytes | None):
            raise PrinterUnreachable("no route")

        submit = composition.make_command_submitter("http://printer:7125", transport)
        outcome = submit("G28", Classification(flags=(), refused=False))
        self.assertFalse(outcome["executed"])
        self.assertIn("unreachable", outcome["reason"])


class ConfigureLoggingTest(unittest.TestCase):
    """configure_logging attaches a stdout handler to the package logger at the chosen level."""

    def setUp(self) -> None:
        """Snapshot and restore the package logger so the test never leaks handler state."""
        logger = logging.getLogger(PACKAGE_LOGGER)
        self._saved_handlers = list(logger.handlers)
        self._saved_level = logger.level
        self._saved_propagate = logger.propagate

    def tearDown(self) -> None:
        """Restore the package logger's handlers, level, and propagation."""
        logger = logging.getLogger(PACKAGE_LOGGER)
        logger.handlers = self._saved_handlers
        logger.setLevel(self._saved_level)
        logger.propagate = self._saved_propagate

    def test_attaches_stdout_stream_handler_at_level(self) -> None:
        """The package logger ends up with a stdout StreamHandler at the requested level."""
        import sys

        configure_logging("WARNING")
        logger = logging.getLogger(PACKAGE_LOGGER)
        self.assertEqual(logger.level, logging.WARNING)
        self.assertFalse(logger.propagate)
        stream_handlers = [
            h for h in logger.handlers if isinstance(h, logging.StreamHandler)
        ]
        self.assertTrue(stream_handlers)
        self.assertTrue(any(h.stream is sys.stdout for h in stream_handlers))
        self.assertEqual(stream_handlers[-1].level, logging.WARNING)

    def test_default_level_is_info_and_emits(self) -> None:
        """An unknown level falls back to INFO and a subsequent logger.info is emitted."""
        configure_logging("not-a-level")
        logger = logging.getLogger(PACKAGE_LOGGER)
        self.assertEqual(logger.level, logging.INFO)
        with self.assertLogs(PACKAGE_LOGGER, level="INFO") as cm:
            logging.getLogger("printer_debugger.composition").info("hello-console")
        self.assertTrue(any("hello-console" in line for line in cm.output))

    def test_idempotent_no_duplicate_handlers(self) -> None:
        """Repeated configuration replaces our handler rather than stacking duplicates."""
        configure_logging("INFO")
        first = len(logging.getLogger(PACKAGE_LOGGER).handlers)
        configure_logging("DEBUG")
        second = len(logging.getLogger(PACKAGE_LOGGER).handlers)
        self.assertEqual(first, second)
        self.assertEqual(logging.getLogger(PACKAGE_LOGGER).level, logging.DEBUG)


if __name__ == "__main__":
    unittest.main()
